apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: flink-bench
  labels:
    app.kubernetes.io/name: flink
    app.kubernetes.io/component: jobmanager
    app.kubernetes.io/part-of: flink-bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flink
      app.kubernetes.io/component: jobmanager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flink
        app.kubernetes.io/component: jobmanager
        app.kubernetes.io/part-of: flink-bench
        state-backend: __STATE_BACKEND__
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9249"
        prometheus.io/path: "/metrics"
    spec:
      nodeSelector:
        volga.io/role: infra
      containers:
        - name: jobmanager
          image: flink:1.20.1
          imagePullPolicy: IfNotPresent
          args: ["jobmanager"]
          ports:
            - name: rpc
              containerPort: 6123
            - name: blob
              containerPort: 6124
            - name: rest
              containerPort: 8081
            - name: metrics
              containerPort: 9249
          env:
            - name: ENABLE_BUILT_IN_PLUGINS
              value: flink-metrics-prometheus;flink-statebackend-rocksdb
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 1536Mi
          volumeMounts:
            - name: flink-config
              mountPath: /opt/flink/conf/config.yaml
              subPath: config.yaml
            - name: flink-job
              mountPath: /opt/flink/job.sql
              subPath: job.sql
      volumes:
        - name: flink-config
          configMap:
            name: flink-config
        - name: flink-job
          configMap:
            name: flink-job
