apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: flink-bench
  labels:
    app.kubernetes.io/name: flink
    app.kubernetes.io/part-of: flink-bench
spec:
  selector:
    app.kubernetes.io/name: flink
    app.kubernetes.io/component: jobmanager
  ports:
    - name: rpc
      port: 6123
      targetPort: rpc
    - name: blob
      port: 6124
      targetPort: blob
    - name: rest
      port: 8081
      targetPort: rest
