apiVersion: volga.io/v1alpha1
kind: VolgaPipeline
metadata:
  name: sample-pipeline
  namespace: default
spec:
  workers:
    replicas: 3
  image: volga:latest
  imagePullPolicy: IfNotPresent
  master:
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "2"
        memory: "2Gi"
  worker:
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "2"
        memory: "2Gi"
  holdOnFinish: true
  pipelineSpec:
    execution_mode: Streaming
    parallelism: 6
    execution_profile:
      MasterWorker:
        num_threads_per_task: 4
    task_assignment_strategy:
      Pipelined:
        slots_per_node: 2
    sources:
      - table_name: test_table
        schema_json: |
          {
            "fields": [
              {
                "name": "value",
                "nullable": false,
                "type": { "name": "utf8" },
                "children": []
              }
            ]
          }
        source:
          Datagen: |
            {
              "rate": null,
              "limit": 60,
              "run_for_s": null,
              "batch_size": 5,
              "fields": {
                "value": { "Key": { "num_unique": 6 } }
              },
              "replayable": true
            }
    sink:
      InMemoryStorageGrpc: |
        {
          "server_addr": "http://volga-test-storage.default.svc.cluster.local:50071"
        }
    sql: "SELECT value FROM test_table"
